config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'static_pages#home'
  get    'sessions/new'
  get    '/help',    to: 'static_pages#help'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/admin.rb
# frozen_string_literal: true

# models a user with admin privileges
class Admin < User
  has_one :company
end

app/models/application_record.rb
# frozen_string_literal: true

# This is an application record class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ceo.rb
# frozen_string_literal: true

# Models a ceo for the company
class Ceo < ApplicationRecord
  belongs_to :company

  validates :salary, presence: true,
                     numericality: { greater_than_or_equal_to: 0 }
end

app/models/comment.rb
# frozen_string_literal: true

# This is a class for writing comments
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  validates :content, presence: true, length: { maximum: 256 }
  validates :author, presence: true
  validates :creation, presence: true
end

app/models/company.rb
# frozen_string_literal: true

# This represents the Company
class Company < ApplicationRecord
  belongs_to :admin
  has_one    :ceo
  has_many   :resources, as: :manageable

  validates :name, uniqueness: true,
                   format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }
  validates :debt, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/human_resource_manager.rb
# frozen_string_literal: true

require 'user'
# Human resource manager class
class HumanResourceManager < User
  has_many :potential_resources
  has_many :resources, as: :manageable
end

app/models/leave_notice.rb
# frozen_string_literal: true

# This is a leave notice class
class LeaveNotice < ApplicationRecord
  belongs_to :resource

  validates :reason, presence: true,
                     format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }
  validates :start, presence: true
  validates :finish, presence: true
end

app/models/potential_resource.rb
# frozen_string_literal: true

# This is a potential resource class
class PotentialResource < ApplicationRecord
  belongs_to :human_resource_manager
  has_many :comments, as: :commentable

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_ALPHA = /\A[^0-9`!@#\$%\^&*+_=]+\z/.freeze

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL }
  validates :name, presence: true, format: { with: VALID_ALPHA }
  validates :last_name, presence: true, format: { with: VALID_ALPHA }
  validates :position, presence: true, format: { with: VALID_ALPHA }
end

app/models/project.rb
# frozen_string_literal: true

# Represents a project manager
class Project < ApplicationRecord
  belongs_to :project_manager
  has_many :comments, as: :commentable
  has_many :resources, as: :manageable

  validates  :name, presence: true, length: { maximum: 100 },
                    format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }
  validates  :resource_reqs, inclusion: 1..30
  validates  :start, presence: true # more validation
  validates  :finish, presence: true # more validation
end

app/models/project_manager.rb
# frozen_string_literal: true

# Represents a project manager
class ProjectManager < User
  MAX_PROJECTS = 5
  has_many :projects, before_add: :validate_project_limit

  def validate_project_limit(_project)
    raise('Too many projects') if projects.size.equal?(MAX_PROJECTS)
  end
end

app/models/resource.rb
# frozen_string_literal: true

# Models a human resource
class Resource < ApplicationRecord
  belongs_to :manageable, polymorphic: true

  has_many   :comments, as: :commentable
  has_many   :leave_notices

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_ALPHA = /\A[^0-9`!@#\$%\^&*+_=]+\z/.freeze

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL }
  validates :name, presence: true, format: { with: VALID_ALPHA }
  validates :last_name, presence: true, format: { with: VALID_ALPHA }
  validates :position, presence: true, format: { with: VALID_ALPHA }
  validates :salary, presence: true,
                     numericality: { greater_than_or_equal_to: 0 }
  validates :birthday, presence: true # more validation
end

app/models/user.rb
# frozen_string_literal: true

# Represents a user
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
  validates :password_confirmation, presence: true, length: { minimum: 8 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :role, presence: true, inclusion:
            { in: %w[admin project_manager hr_manager ceo] }
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# controls session
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params.fetch(:session).fetch(:email))
    if user&.authenticate(params.fetch(:session).fetch(:password))
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# controls users
class UsersController < ApplicationController
  def show
    @user = User.find(params.key?(:id))
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation,
                                 :name, :last_name, :role)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# documentation
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# documentation
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# helps the session
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

# helps static pages
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# helps users
module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# documentation
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>
    <div class='container'>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>  
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>